homeassistant:
  unit_system: metric
  temperature_unit: C
  currency: KRW
  customize: !include ./include/customize.yaml
  allowlist_external_dirs:
    - /config
    
default_config:
  
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret ha_address
    - 172.30.33.0/24

lovelace:
  mode: yaml
  resources:
    [ {url: /hacsfiles/button-card/button-card.js,                                          type: module},
      {url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,                           type: module},
      {url: /hacsfiles/lovelace-card-mod/card-mod.js,                                       type: module},
      {url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js,                    type: module},
      {url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,                     type: module},
      {url: /hacsfiles/lovelace-layout-card/layout-card.js,                                 type: module},
      {url: /hacsfiles/mini-media-player/mini-media-player-bundle.js,                       type: module},
      {url: /hacsfiles/battery-state-card/battery-state-card.js,                            type: module},
      {url: /hacsfiles/lovelace-hui-element/hui-element.js,                                 type: module},
      {url: /hacsfiles/light-popup-card/light-popup-card.js,                                type: module},
      {url: /hacsfiles/light-entity-card/light-entity-card.js,                              type: module},
      {url: /hacsfiles/bar-card/bar-card.js,                                                type: module},
      {url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js,                   type: module},
      {url: /hacsfiles/swipe-card/swipe-card.js,                                            type: module},

      {url: /local/file-loader.js,                                                          type: module},
      {url: /local/fonts.css,                                                               type: css   } ]

# includes
frontend:
  themes: !include ./include/themes.yaml

automation: !include ./automations.yaml
group: !include ./include/group.yaml
input_boolean: !include ./include/input_boolean.yaml
input_select: !include ./include/input_select.yaml
scene: !include ./scenes.yaml
script: !include ./scripts.yaml
sensor: !include ./include/sensor.yaml
switch: !include ./include/switch.yaml
template: !include ./include/template.yaml
fan: !include ./include/fan.yaml

webostv:
  host: !secret  living_room_tv_ip_addr
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret living_room_tv_mac_addr

logger:
  default: warning
  logs:
    homeassistant.components.rest_command: fatal

recorder:
  db_url: !secret recorder_db_url

# Cloud
cloud:

discovery:
  ignore:
    - yeelight

yeelight:
  devices:
    192.168.0.33:
      name: Xiaomi Desk Strip
      save_on_change: true

wake_on_lan:

browser_mod:

tts:
  - platform: google_translate
  - platform: kakao_tts
    api_key: !secret kakao_api
    voice: 'MAN_DIALOG_BRIGHT'
    volume: 'soft'