homeassistant:
  name: StanSign
  unit_system: metric
  temperature_unit: C
  currency: KRW
  packages: !include_dir_named include
  allowlist_external_dirs:
    - /config
    
default_config:

lovelace:
  mode: yaml
  resources:
    [ {url: /hacsfiles/button-card/button-card.js,                                          type: module},
      {url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,                           type: module},
      {url: /hacsfiles/lovelace-card-mod/card-mod.js,                                       type: module},
      {url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js,                    type: module},
      {url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,                     type: module},
      {url: /hacsfiles/lovelace-layout-card/layout-card.js,                                 type: module},
      {url: /hacsfiles/mini-media-player/mini-media-player-bundle.js,                       type: module},
      {url: /hacsfiles/battery-state-card/battery-state-card.js,                            type: module},
      {url: /hacsfiles/lovelace-hui-element/hui-element.js,                                 type: module},
      {url: /hacsfiles/light-popup-card/light-popup-card.js,                                type: module},
      {url: /hacsfiles/light-entity-card/light-entity-card.js,                              type: module},
      {url: /hacsfiles/bar-card/bar-card.js,                                                type: module},
      {url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js,                   type: module},
      {url: /hacsfiles/swipe-card/swipe-card.js,                                            type: module},

      {url: /local/file-loader.js,                                                          type: module},
      {url: /local/fonts.css,                                                               type: css   } ]

logger:
  default: warning
  logs:
    homeassistant.helpers.entity: fatal

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 5
  commit_interval: 30
  exclude:
    entity_globs:
      - sensor.browser_*

person:
  - name: ChangJun
    id: changjun
    device_trackers:
      - device_tracker.stansign_iphone

yeelight:
  devices:
    192.168.0.33:
      name: Xiaomi Desk Strip
      save_on_change: true

browser_mod:
  prefix: browser_

tts:
  - platform: google_translate