homeassistant:

    ####################################################
    #                                                  #
    #                    CUSTOMIZE                     #
    #                                                  #
    ####################################################

  customize_domain:
    automation:
      initial_state: true

  customize: