sensor:
  - unique_id: sidebar
    state: template
    attributes:
      time: >
        {% set hours = now().strftime('%H') %}
        {% set minutes = now().strftime('%M') %}
        <span class="time">
          {{ hours }}<span class="time-colon">:</span>{{ minutes }}
        </span>
      date: |
        <font color='#6a7377'><b>
        {%- if strptime(states('sensor.date'), '%Y-%m-%d').day != null %}
        {%- set days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %}
        {%- set months = ['January', 'Feburary', 'Mars', 'April', 'May', 'June', 
        'July', 'August', 'September', 'October', 'November', 'December'] %}
          {{- days[now().weekday()] }}<br>
          {{- strptime(states('sensor.date'), '%Y-%m-%d').day }} {{ months[now().month-1] }}
        {%- endif -%}
        </b></font>
      greet: |
        <b>
        {%- set time = now().hour %}
        {%- if time <= 1 -%} Good Night {{'\U0001F611'}}
        {%- elif time <= 3 -%} Good Night {{'\U0001F62A'}}
        {%- elif time <= 5 -%} Good Night {{'\U0001F634'}}
        {%- elif time <= 7 -%} Good Morning {{'\U0001F4A9'}}
        {%- elif time <= 9 -%} Good Morning {{'\u2615\uFE0F'}}
        {%- elif time <= 10 -%} Good Morning {{'\U0001F642'}}
        {%- elif time <= 13 -%} Good Day {{'\U0001F60A'}}
        {%- elif time <= 15 -%} Good Day {{'\U0001F60E'}}
        {%- elif time <= 17 -%} Good Day {{'\U0001F44B\U0001F3FB'}}
        {%- elif time <= 19 -%} Good Evening {{'\U0001F44B\U0001F3FB'}}
        {%- elif time <= 22 -%} Good Evening {{'\U0001F60C'}}
        {%- elif time <= 23 -%} Good Evening {{'\U0001F974'}}
        {%- else %} Good Evening {{'\U0001F974'}}
        {%- endif -%}
        </b>

      # 온도, 맑음, 강수
      weather: |
        {%- set temperature = states('sensor.naver_weather_nowtemp_1') %}
        {%- set precip = states('sensor.naver_weather_rainpercent_1') | round %}
        {% if not is_state('sensor.naver_weather_nowtemp_1', 'unknown') %}
          {%- if temperature | float <= 0.0 -%}
            Currently {{ temperature }}°C with {{ precip }}% risk of snow {{'\u2744\uFE0F'}}
          {%- elif temperature | float > 0.0 -%} 
            Currently {{ temperature}}°C with {{ precip }}% risk of rain {{ '\u2614\uFE0F' if precip > 30 }}
          {%- endif %}
        {%- else %}
          Failed to load weather information...
        {%- endif %}

      humidity: |
        {%- set humidity = states('sensor.air_monitor_humidity') %}
        {% if not is_state('sensor.air_monitor_humidity', 'unknown') %}
          {%- if humidity | int <= 55 -%}
            Currently {{ humidity }}%, make your room humid {{'\uD83D\uDCA7'}}
          {%- endif %}
        {%- else %}
          Failed to load humidity information...
        {%- endif %}

      co2: |
        {%- set co2 = states('sensor.air_monitor_co2') %}
        {% if not is_state('sensor.air_monitor_co2', 'unknown') %}
          {%- if co2 | float >= 1000 -%}
            Currently {{ co2 }}ppm, air out your room {{'\uDBBA\uDF5D'}}
          {%- endif %}
        {%- else %}
          Failed to load CO2 information...
        {%- endif %}

      pm25: |
        {%- set pm25 = states('sensor.air_monitor_pm2_5_density') %}
        {% if not is_state('sensor.air_monitor_pm2_5_density', 'unknown') %}
          {%- if pm25 | float >= 50 -%}
            Currently {{ pm25 }}ppm, air out your room {{'\uDBBA\uDF5D'}}
          {%- endif %}
        {%- else %}
          Failed to load PM2.5 information...
        {%- endif %}

      pm10: |
        {%- set pm10 = states('sensor.air_monitor_pm10_density') %}
        {% if not is_state('sensor.air_monitor_pm10_density', 'unknown') %}
          {%- if pm10 | float >= 100 -%}
            Currently {{ pm10 }}ppm, air out your room {{'\uDBBA\uDF5D'}}
          {%- endif %}
        {%- else %}
          Failed to load PM10 information...
        {%- endif %}

      battery: |
        {% set entities = [
          'sensor.pressure_balcony_battery',
          'sensor.motion_sensor_battery',
          'sensor.door_sensor_battery',
          'sensor.air_monitor_battery' ] %}
        {%- for sensor in entities if states(sensor) | int <= 5 and states(sensor) != 'unknown' %}
          {%- if loop.first %} {{-'\u26A0\uFE0F'}} {% else %}, {% endif -%}
          {{ state_attr(sensor, 'friendly_name') + ' ' +  states(sensor) + '%' }}
        {%- endfor %}

  - unique_id: hacs_version
    state: >
      {{ device_attr(device_id('sensor.hacs'), 'sw_version') }}
